name: android

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: [self-hosted, winbuild]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run build script
      run: ./deploy.ps1 -RepoUrl ${{ secrets.TEST_REPO_URL }} -User ${{ secrets.TEST_USER }} -Pwd ${{ secrets.TEST_PWD }}
  